name: storeit
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  adaptive_dialog: ^2.4.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.7.0
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  geolocator: ^14.0.1
  get_it: ^9.0.5
  injectable: ^2.5.0
  jwt_decode: ^0.3.1
  localizations:
    path: localizations
  material_symbols_icons: ^4.2892.0
  package_info_plus: ^8.3.0
  pretty_dio_logger: ^1.4.0
  retrofit: 4.9.1
  collection: ^1.18.0

dev_dependencies:
  analyzer: ^7.7.1
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_flavorizr: ^2.2.3
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  intl: ^0.20.2
  json_serializable: ^6.8.0
  lottie: ^3.3.1
  melos: ^7.2.0
  mocktail: ^1.0.4
  retrofit_generator: ^10.0.6

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0


flutter_gen:
  output: lib/core/utils/generated
  assets:
    outputs:
      class_name: StoreItAssets
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  assets:
    - assets/icons/Bold/
    - assets/icons/Bold/Arrows
    - assets/icons/Bold/ArrowsAction/
    - assets/icons/Bold/Astronomy/
    - assets/icons/Bold/BuildingInfrastructure/
    - assets/icons/Bold/BusinessStatistic/
    - assets/icons/Bold/Call/
    - assets/icons/Bold/DesignTools/
    - assets/icons/Bold/ElectronicDevices/
    - assets/icons/Bold/EssentionalUI/
    - assets/icons/Bold/FacesEmotionsStickers/
    - assets/icons/Bold/Files/
    - assets/icons/Bold/Folders/
    - assets/icons/Bold/FoodKitchen/
    - assets/icons/Bold/Hands/
    - assets/icons/Bold/HomeFurniture/
    - assets/icons/Bold/Like/
    - assets/icons/Bold/List/
    - assets/icons/Bold/MapLocation/
    - assets/icons/Bold/Medicine/
    - assets/icons/Bold/MessagesConversation/
    - assets/icons/Bold/Money/
    - assets/icons/Bold/NatureTravel/
    - assets/icons/Bold/NetworkITProgramming/
    - assets/icons/Bold/Notes/
    - assets/icons/Bold/Notifications/
    - assets/icons/Bold/School/
    - assets/icons/Bold/Search/
    - assets/icons/Bold/Security/
    - assets/icons/Bold/SettingsFineTuning/
    - assets/icons/Bold/ShoppingEcommerce/
    - assets/icons/Bold/Sports/
    - assets/icons/Bold/TextFormatting/
    - assets/icons/Bold/Time/
    - assets/icons/Bold/TransportPartsService/
    - assets/icons/Bold/Users/
    - assets/icons/Bold/VideoAudioSound/
    - assets/icons/Bold/Weather/

# OutlineÂ¬
    - assets/icons/Outline/
    - assets/icons/Outline/Arrows
    - assets/icons/Outline/ArrowsAction/
    - assets/icons/Outline/Astronomy/
    - assets/icons/Outline/BuildingInfrastructure/
    - assets/icons/Outline/BusinessStatistic/
    - assets/icons/Outline/Call/
    - assets/icons/Outline/DesignTools/
    - assets/icons/Outline/ElectronicDevices/
    - assets/icons/Outline/EssentionalUI/
    - assets/icons/Outline/FacesEmotionsStickers/
    - assets/icons/Outline/Files/
    - assets/icons/Outline/Folders/
    - assets/icons/Outline/FoodKitchen/
    - assets/icons/Outline/Hands/
    - assets/icons/Outline/HomeFurniture/
    - assets/icons/Outline/Like/
    - assets/icons/Outline/List/
    - assets/icons/Outline/MapLocation/
    - assets/icons/Outline/Medicine/
    - assets/icons/Outline/MessagesConversation/
    - assets/icons/Outline/Money/
    - assets/icons/Outline/NatureTravel/
    - assets/icons/Outline/NetworkITProgramming/
    - assets/icons/Outline/Notes/
    - assets/icons/Outline/Notifications/
    - assets/icons/Outline/School/
    - assets/icons/Outline/Search/
    - assets/icons/Outline/Security/
    - assets/icons/Outline/SettingsFineTuning/
    - assets/icons/Outline/ShoppingEcommerce/
    - assets/icons/Outline/Sports/
    - assets/icons/Outline/TextFormatting/
    - assets/icons/Outline/Time/
    - assets/icons/Outline/TransportPartsService/
    - assets/icons/Outline/Users/
    - assets/icons/Outline/VideoAudioSound/
    - assets/icons/Outline/Weather/


  uses-material-design: true


